routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// route auth login dan register
Auth::routes();

Route::middleware(['guest'])->group(function(){
	Route::get('/', 'AuthController@getLogin')->name('login');
	Route::post('postlogin', 'AuthController@postLogin')->name('postlogin');
	Route::get('resetPassword', 'AuthController@resetPassword')->name('resetPassword');
	Route::post('postReset', 'AuthController@postReset')->name('postReset');
});

Route::middleware(['web', 'auth'])->group(function(){

	Route::middleware(['admin'])->group(function(){
		Route::get('admin', 'DashboardController@index')->name('admin');
		Route::resource('ibu', 'IbuController');
		Route::resource('anak', 'AnakController');
		Route::resource('ibuhamil', 'IbuHamilController');
		Route::post('bumil_meninggal', 'IbuHamilController@meninggal')->name('bumil_meninggal');
		Route::post('bumil_melahirkan', 'IbuHamilController@melahirkan')->name('bumil_melahirkan');
		Route::resource('kader', 'KaderController');
		Route::post('kaderStore1', 'KaderController@store1')->name('kaderStore1');
		Route::resource('pengguna', 'PenggunaController');
		Route::get('generatePwd/{id}', 'PenggunaController@generatePwd')->name('generatePwd');
		Route::resource('agenda', 'AgendaController');

		Route::resource('bukutamu', 'BukuTamuController');
		Route::get('checkrelasi/{id}', 'BukuTamuController@checkrelasi')->name('checkrelasi');
		Route::get('deleteBukuTamu/{id}', 'BukuTamuController@hapus');

		Route::resource('timbang', 'TimbangController');
		// timbang utk ibu


		Route::resource('imunisasi', 'ImunisasiController');
		Route::resource('vitA', 'VitAController');
		Route::resource('kegiatan', 'KegiatanController');
		Route::resource('jenisimunisasi', 'JenisImunisasiController');
		Route::resource('kehadiran', 'KehadiranController');
		Route::resource('laporan', 'LaporanController');

		Route::get('printAnak', 'AnakController@printAnak')->name('printAnak');
		Route::get('form1', 'LaporanController@form1')->name('form1');
		Route::get('form2', 'LaporanController@form2')->name('form2');
		Route::get('form3', 'LaporanController@form3')->name('form3');
		Route::get('form4', 'LaporanController@form4')->name('form4');
		Route::get('form5', 'LaporanController@form5')->name('form5');
		Route::get('form6', 'LaporanController@form6')->name('form6');
		Route::get('form7', 'LaporanController@form7')->name('form7');

		// UKM dan PKK Route
		Route::get('viewPKK', 'KegiatanController@viewPKK')->name('viewPKK');
		Route::post('storePKK', 'KegiatanController@storePKK')->name('storePKK');
		Route::get('editPKK/{id}', 'KegiatanController@editPKK')->name('editPKK');
		Route::post('updatePKK/{id}', 'KegiatanController@updatePKK')->name('updatePKK');
		Route::get('deletePKK/{id}', 'KegiatanController@deletePKK')->name('deletePKK');

		Route::get('checkindependensi/{id}', 'KegiatanController@checkindependensi')->name('checkindependensi');

		Route::get('checkindependensiukm/{id}', 'KegiatanController@checkindependensiukm')->name('checkindependensiukm');

		Route::get('viewUKM', 'KegiatanController@viewUKM')->name('viewUKM');
		Route::post('storeUKM', 'KegiatanController@storeUKM')->name('storeUKM');
		Route::get('editUKM/{id}', 'KegiatanController@editUKM')->name('editUKM');
		Route::post('updateUKM/{id}', 'KegiatanController@updateUKM')->name('updateUKM');
		Route::get('deleteUKM/{id}', 'KegiatanController@deleteUKM')->name('deleteUKM');
		/////////////

		// Status Gizi, BGM dan 2T
		Route::resource('statusgizi', 'StatusController');
		Route::get('bgm2t', 'StatusController@viewBGM')->name('viewBGM');
		/////////////

		// Gallery Route
		Route::get('albumList', 'AgendaController@albumList')->name('albumList');
		Route::post('albumStore', 'AgendaController@albumStore')->name('albumStore');
		Route::get('albumDetail/{id}', 'AgendaController@albumDetail')->name('albumDetail');
		Route::get('albumDelete/{id}', 'AgendaController@albumStore')->name('albumDelete');
		// Route::get('viewImage', 'AgendaController@viewImage')->name('viewImage');
		Route::get('addImage/{id}', 'AgendaController@addImage')->name('addImage');
		Route::post('storeImage', 'AgendaController@storeImage')->name('storeImage');
		Route::get('deleteImage/{id}', 'AgendaController@deleteImage')->name('deleteImage');

		Route::get('printAbsen/{id}', 'AgendaController@printAbsen')->name('printAbsen');
		/////////////

		// Export Excel
		Route::get('exportIbu', 'IbuController@exportIbu')->name('exportIbu');
		Route::get('exportAnak', 'AnakController@exportAnak')->name('exportAnak');
		/////////////
	});

	Route::middleware(['user'])->group(function(){
		// Route::get('user', function (){
		// 	return view('user.dashboard');
		// })->name('user');

		Route::get('user', 'IbuTimbangController@dashboard')->name('user');

		Route::get('user/anak', 'IbuTimbangController@getAnak');
		Route::get('user/timbang', 'IbuTimbangController@index')->name('timbanguser');
		Route::get('user/imunisasi', 'IbuImunisasiController@index');
		Route::get('user/vitamin', 'IbuVitaminController@index');
		Route::get('user/tumbuh/{id}', 'IbuTimbangController@detailanak')->name('tumbuhanak');

	});

	Route::get('getProfile', 'DashboardController@getProfile')->name('getProfile');
	Route::post('postProfile', 'DashboardController@postProfile')->name('postProfile');
	Route::get('logout', 'DashboardController@getLogout')->name('logout');
});



// Route::middleware(['web', 'auth'])->group(function (){

// 	Route::get('/', 'DashboardController@index');

// 	Route::middleware(['admin'])->group(function(){
// 		Route::get('admin', function (){
// 			return view('admin.dashboard');
// 		});
// 		Route::resource('ibu', 'IbuController');
// 		Route::resource('anak', 'AnakController');
// 		Route::resource('ibuhamil', 'IbuHamilController');
// 		Route::resource('kader', 'KaderController');
// 		Route::resource('pengguna', 'PenggunaController');
// 		Route::resource('agenda', 'AgendaController');
// 		Route::resource('bukutamu', 'BukuTamuController');
// 		Route::resource('timbang', 'TimbangController');
// 		Route::resource('vitA', 'VitAController');
// 		Route::resource('kegiatan', 'KegiatanController');
// 		Route::resource('jenisimunisasi', 'JenisImunisasiController');
// 	});

// 	Route::middleware(['user'])->group(function(){
// 		Route::get('user', function (){
// 			return view('user.dashboard');
// 		});
// 	});
// });


Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/dashboard.blade.php
@extends('layouts.base')

@section('breadcrumb')
<h1>
    Dashboard
    <small>Overview</small>
</h1>
<ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">Dashboard</li>
</ol>
@endsection

@section('css')
<!-- fullCalendar -->
<link rel="stylesheet" href="{!! asset('bower_components/fullcalendar/dist/fullcalendar.min.css') !!}">
<link rel="stylesheet" href="{!! asset('bower_components/fullcalendar/dist/fullcalendar.print.min.css') !!}" media="print">
@endsection

@section('content')
<!-- Small boxes (Stat box) -->
<div class="row">
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-aqua">
            <div class="inner">
                <h3>{{ $data1 }}</h3>
                <p>Ibu</p>
            </div>
            <div class="icon">
                <i class="fa fa-female"></i>
            </div>
            <a href="{{ route('ibu.index') }}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-green">
            <div class="inner">
                <h3>{{ $data2 }}</h3>
                <p>Anak</p>
            </div>
            <div class="icon">
                <i class="fa fa-child"></i>
            </div>
            <a href="{{ route('anak.index') }}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-yellow">
            <div class="inner">
                <h3>{{ $data3 }}</h3>
                <p>Kader</p>
            </div>
            <div class="icon">
                <i class="fa fa-user-md"></i>
            </div>
            <a href="{{ route('kader.index') }}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-red">
            <div class="inner">
                <h3>{{ $data4 }}</h3>
                <p>Pengguna</p>
            </div>
            <div class="icon">
                <i class="fa fa-user"></i>
            </div>
            <a href="{{ route('pengguna.index') }}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
</div>
<!-- /.row -->

<!-- Main row -->
<div class="row">
    <!-- right col (We are only adding the ID to make the widgets sortable)-->
    <section class="col-lg-5">
        <!-- Calendar -->
        <div class="box box-solid bg-solid-gradient">
            <div class="box-header">
                <i class="fa fa-calendar"></i>
                <h3 class="box-title" style="color: black;"><i class="fa fa-calendar" aria-hidden="true"></i> Calendar</h3>
                <!-- tools box -->
                <div class="pull-right box-tools">
                    <button type="button" class="btn btn-success btn-sm" data-widget="collapse"><i class="fa fa-minus"></i></button>
                </div>
                <!-- /. tools -->
            </div>
            <!-- /.box-header -->
            <div class="box-body no-padding">
                <!--The calendar -->
                {!! $calendar->calendar() !!}
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </section>
    <!-- right col -->
    
    <!-- Left col -->
    <section class="col-lg-7">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">
                    Rekap Data Anak Tahun @php echo date("Y"); @endphp
                </h3>
                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="chart">
                            <!-- Sales Chart Canvas -->
                            <div id="chart1" style="height: 420px;"></div>
                            {!! $chart1 !!}
                        </div>
                        <!-- /.chart-responsive -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- ./box-body -->
        </div>
        <!-- /.box -->
    </section>
    <!-- /.Left col -->
</div>
<!-- /.row (main row) -->
@endsection

@section('java')
<!-- fullCalendar -->
<script src="{!! asset('bower_components/moment/moment.js') !!}"></script>
<script src="{!! asset('bower_components/fullcalendar/dist/fullcalendar.min.js') !!}"></script>
<!-- highchart -->
<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="http://code.highcharts.com/modules/exporting.js"></script>

<script>
function myFunction() {
    var checkBox = document.getElementById("todo-check");
    var text = document.getElementById("todo-text");
    if (checkBox.checked == true){
        // text.style.display = "none";
        text.style.textDecoration = "line-through"
        text.style.fontWeight = "normal"
    } else {
        // text.style.display = "block";
        text.style.textDecoration = "none"
        text.style.fontWeight = "bold"
    }
}
</script>

{!! $calendar->script() !!}
@endsection

resources/views/admin/profile.blade.php
@extends('layouts.base')

@section('breadcrumb')
<h1>
    Profile
    <small></small>
</h1>
<ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">Profile</li>
</ol>
@endsection

@section('css')

@endsection

@section('content')

@if ($message = Session::get('success'))
    <div class="alert alert-success alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <h4><i class="icon fa fa-check"></i> Berhasil!</h4>
        {{ $message }}
    </div>
@endif

<div class="panel panel-default">
    <div class="panel-heading">Edit Profile</div>
    <div class="panel-body">
        <div class="container">
            <div class="row">
                <div class="col-md-9">
                    <form class="form-horizontal" method="post" action="{{ route('postProfile') }}">
                        @csrf
                        <div class="form-group">
                            <div class="row">
                                <label class="col-md-4 control-label" for="email">Email</label>
                                <div class="input-group col-md-8">
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-envelope" aria-hidden="true"></i></span>
                                        <input type="email" class="form-control" placeholder="Email" name="email" required value="{{Auth::user()->email}}">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <label class="col-md-4 control-label" for="oldPassword">Password Lama</label>
                                <div class="input-group col-md-8">
                                    <div class="input-group" style="">
                                        <span class="input-group-addon"><i class="fa fa-lock" aria-hidden="true"></i></span>
                                        <input type="password" class="form-control" placeholder="Password Lama" name="oldPassword" id="oldPassword">

                                        <span class="input-group-addon show-password"><i class="fa fa-eye" aria-hidden="true"></i></span>
                                        <span class="input-group-addon hide-password" style="display: none;"><i class="fa fa-eye-slash" aria-hidden="true"></i></span>
                                    </div>
                                    @if ($message = Session::get('pwdLama'))
                                        <div>
                                            <p style="color: red"><i class="fa fa-exclamation-triangle" aria-hidden="true"></i> {{ $message }}</p>
                                        </div>
                                    @endif
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <label class="col-md-4 control-label" for="newPassword">Password Baru</label>
                                <div class="input-group col-md-8">
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-lock" aria-hidden="true"></i></span>
                                        <input type="password" class="form-control" placeholder="Password Baru" name="newPassword" id="newPassword">
                                        
                                        <span class="input-group-addon show-password"><i class="fa fa-eye" aria-hidden="true"></i></span>
                                        <span class="input-group-addon hide-password" style="display: none;"><i class="fa fa-eye-slash" aria-hidden="true"></i></span>
                                    </div>
                                    @if ($message = Session::get('pwdBaru'))
                                        <div>
                                            <p style="color: red"><i class="fa fa-exclamation-triangle" aria-hidden="true"></i> {{ $message }}</p>
                                        </div>
                                    @endif
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <label class="col-md-4 control-label" for="confirmPassword">Konfirmasi Password</label>
                                <div class="input-group col-md-8">
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-lock" aria-hidden="true"></i></span>
                                        <input type="password" class="form-control" placeholder="Konfirmasi Password" name="confirmPassword" id="confirmPassword">
                                        
                                        <span class="input-group-addon show-password"><i class="fa fa-eye" aria-hidden="true"></i></span>
                                        <span class="input-group-addon hide-password" style="display: none;"><i class="fa fa-eye-slash" aria-hidden="true"></i></span>
                                    </div>
                                    @if ($message = Session::get('pwdConf'))
                                        <div>
                                            <p style="color: red"><i class="fa fa-exclamation-triangle" aria-hidden="true"></i> {{ $message }}</p>
                                        </div>
                                    @endif
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <label class="col-md-4 control-label" for="name"></label>
                                <div class="input-group col-md-8">
                                    <button type="submit" class="btn btn-primary" style="margin-right: 6px;">Update</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-md-3"></div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('java')
<script>
    $(document).ready(function() {
        $(".show-password, .hide-password").on('click', function() {
            var passwordId = $(this).parents('div:first').find('input').attr('id');
            if ($(this).hasClass('show-password')) {
                $("#" + passwordId).attr("type", "text");
                $(this).parent().find(".show-password").hide();
                $(this).parent().find(".hide-password").show();
            } else {
                $("#" + passwordId).attr("type", "password");
                $(this).parent().find(".hide-password").hide();
                $(this).parent().find(".show-password").show();
            }
        });
    });
</script>
@endsection