routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// route auth login dan register
Auth::routes();

Route::middleware(['guest'])->group(function(){
	Route::get('/', 'AuthController@getLogin')->name('login');
	Route::post('postlogin', 'AuthController@postLogin')->name('postlogin');
	Route::get('resetPassword', 'AuthController@resetPassword')->name('resetPassword');
	Route::post('postReset', 'AuthController@postReset')->name('postReset');
});

Route::middleware(['web', 'auth'])->group(function(){

	Route::middleware(['admin'])->group(function(){
		Route::get('admin', 'DashboardController@index')->name('admin');
		Route::resource('ibu', 'IbuController');
		Route::resource('anak', 'AnakController');
		Route::resource('ibuhamil', 'IbuHamilController');
		Route::post('bumil_meninggal', 'IbuHamilController@meninggal')->name('bumil_meninggal');
		Route::post('bumil_melahirkan', 'IbuHamilController@melahirkan')->name('bumil_melahirkan');
		Route::resource('kader', 'KaderController');
		Route::post('kaderStore1', 'KaderController@store1')->name('kaderStore1');
		Route::resource('pengguna', 'PenggunaController');
		Route::get('generatePwd/{id}', 'PenggunaController@generatePwd')->name('generatePwd');
		Route::resource('agenda', 'AgendaController');

		Route::resource('bukutamu', 'BukuTamuController');
		Route::get('checkrelasi/{id}', 'BukuTamuController@checkrelasi')->name('checkrelasi');
		Route::get('deleteBukuTamu/{id}', 'BukuTamuController@hapus');

		Route::resource('timbang', 'TimbangController');
		// timbang utk ibu


		Route::resource('imunisasi', 'ImunisasiController');
		Route::resource('vitA', 'VitAController');
		Route::resource('kegiatan', 'KegiatanController');
		Route::resource('jenisimunisasi', 'JenisImunisasiController');
		Route::resource('kehadiran', 'KehadiranController');
		Route::resource('laporan', 'LaporanController');

		Route::get('printAnak', 'AnakController@printAnak')->name('printAnak');
		Route::get('form1', 'LaporanController@form1')->name('form1');
		Route::get('form2', 'LaporanController@form2')->name('form2');
		Route::get('form3', 'LaporanController@form3')->name('form3');
		Route::get('form4', 'LaporanController@form4')->name('form4');
		Route::get('form5', 'LaporanController@form5')->name('form5');
		Route::get('form6', 'LaporanController@form6')->name('form6');
		Route::get('form7', 'LaporanController@form7')->name('form7');

		// UKM dan PKK Route
		Route::get('viewPKK', 'KegiatanController@viewPKK')->name('viewPKK');
		Route::post('storePKK', 'KegiatanController@storePKK')->name('storePKK');
		Route::get('editPKK/{id}', 'KegiatanController@editPKK')->name('editPKK');
		Route::post('updatePKK/{id}', 'KegiatanController@updatePKK')->name('updatePKK');
		Route::get('deletePKK/{id}', 'KegiatanController@deletePKK')->name('deletePKK');

		Route::get('checkindependensi/{id}', 'KegiatanController@checkindependensi')->name('checkindependensi');

		Route::get('checkindependensiukm/{id}', 'KegiatanController@checkindependensiukm')->name('checkindependensiukm');

		Route::get('viewUKM', 'KegiatanController@viewUKM')->name('viewUKM');
		Route::post('storeUKM', 'KegiatanController@storeUKM')->name('storeUKM');
		Route::get('editUKM/{id}', 'KegiatanController@editUKM')->name('editUKM');
		Route::post('updateUKM/{id}', 'KegiatanController@updateUKM')->name('updateUKM');
		Route::get('deleteUKM/{id}', 'KegiatanController@deleteUKM')->name('deleteUKM');
		/////////////

		// Status Gizi, BGM dan 2T
		Route::resource('statusgizi', 'StatusController');
		Route::get('bgm2t', 'StatusController@viewBGM')->name('viewBGM');
		/////////////

		// Gallery Route
		Route::get('albumList', 'AgendaController@albumList')->name('albumList');
		Route::post('albumStore', 'AgendaController@albumStore')->name('albumStore');
		Route::get('albumDetail/{id}', 'AgendaController@albumDetail')->name('albumDetail');
		Route::get('albumDelete/{id}', 'AgendaController@albumStore')->name('albumDelete');
		// Route::get('viewImage', 'AgendaController@viewImage')->name('viewImage');
		Route::get('addImage/{id}', 'AgendaController@addImage')->name('addImage');
		Route::post('storeImage', 'AgendaController@storeImage')->name('storeImage');
		Route::get('deleteImage/{id}', 'AgendaController@deleteImage')->name('deleteImage');

		Route::get('printAbsen/{id}', 'AgendaController@printAbsen')->name('printAbsen');
		/////////////

		// Export Excel
		Route::get('exportIbu', 'IbuController@exportIbu')->name('exportIbu');
		Route::get('exportAnak', 'AnakController@exportAnak')->name('exportAnak');
		/////////////
	});

	Route::middleware(['user'])->group(function(){
		// Route::get('user', function (){
		// 	return view('user.dashboard');
		// })->name('user');

		Route::get('user', 'IbuTimbangController@dashboard')->name('user');

		Route::get('user/anak', 'IbuTimbangController@getAnak');
		Route::get('user/timbang', 'IbuTimbangController@index')->name('timbanguser');
		Route::get('user/imunisasi', 'IbuImunisasiController@index');
		Route::get('user/vitamin', 'IbuVitaminController@index');
		Route::get('user/tumbuh/{id}', 'IbuTimbangController@detailanak')->name('tumbuhanak');

	});

	Route::get('getProfile', 'DashboardController@getProfile')->name('getProfile');
	Route::post('postProfile', 'DashboardController@postProfile')->name('postProfile');
	Route::get('logout', 'DashboardController@getLogout')->name('logout');
});



// Route::middleware(['web', 'auth'])->group(function (){

// 	Route::get('/', 'DashboardController@index');

// 	Route::middleware(['admin'])->group(function(){
// 		Route::get('admin', function (){
// 			return view('admin.dashboard');
// 		});
// 		Route::resource('ibu', 'IbuController');
// 		Route::resource('anak', 'AnakController');
// 		Route::resource('ibuhamil', 'IbuHamilController');
// 		Route::resource('kader', 'KaderController');
// 		Route::resource('pengguna', 'PenggunaController');
// 		Route::resource('agenda', 'AgendaController');
// 		Route::resource('bukutamu', 'BukuTamuController');
// 		Route::resource('timbang', 'TimbangController');
// 		Route::resource('vitA', 'VitAController');
// 		Route::resource('kegiatan', 'KegiatanController');
// 		Route::resource('jenisimunisasi', 'JenisImunisasiController');
// 	});

// 	Route::middleware(['user'])->group(function(){
// 		Route::get('user', function (){
// 			return view('user.dashboard');
// 		});
// 	});
// });


Route::get('/home', 'HomeController@index')->name('home');

app/JenisImunisasi.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class JenisImunisasi extends Model
{
    protected $table = 'jenis_imunisasis';
    protected $primaryKey = 'id_j_imun';

    public function imunisasi()
    {
        return $this->hasMany('App\Imunisasi', 'id_j_imun');
    }
}

app/Http/Controllers/JenisImunisasiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\JenisImunisasi;
use App\Imunisasi;
use Illuminate\Support\Facades\DB;

class JenisImunisasiController extends Controller
{
    public function __construct()
    {
        $this->middleware('admin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = JenisImunisasi::orderBy('umur', 'asc')->get();
        return view('admin.jenisimunisasi.view', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.jenisimunisasi.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data             = new JenisImunisasi;
        $data->nama_imun  = $request->get('nama_imun');
        $data->umur       = $request->get('umur');
        $data->save();

        return redirect()->route('jenisimunisasi.index')->with(['success' => 'Data Berhasil Di Tambah']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = JenisImunisasi::where('id_j_imun', $id)->get();
        return view('admin.jenisimunisasi.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = JenisImunisasi::where('id_j_imun', $id)->first();
        $data->nama_imun  = $request->get('nama_imun');
        $data->umur       = $request->get('umur');
        $data->save();

        return redirect()->route('jenisimunisasi.index')->with(['success' => 'Data Berhasil Di Update']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $imunisasi = Imunisasi::where('id_j_imun', $id)->delete();
        $data = JenisImunisasi::where('id_j_imun', $id)->first();
        $data->delete();
        return redirect()->route('jenisimunisasi.index')->with(['success' => 'Data Berhasil Di Hapus']);
    }
}

resources/views/admin/jenisimunisasi/create.blade.php
@extends('layouts.base')

@section('css')
<!-- bootstrap datepicker -->
<link rel="stylesheet" href="{!! asset('bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css') !!}">
<!-- iCheck for checkboxes and radio inputs -->
  <link rel="stylesheet" href="{!! asset('plugins/iCheck/all.css') !!}">
<!-- Select2 -->
  <link rel="stylesheet" href="{!! asset('bower_components/select2/dist/css/select2.min.css') !!}">
@endsection

@section('breadcrumb')
<h1>
    Jenis Imunisasi
    <small>kelola data jenis imunisasi</small>
</h1>
<ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="#">Data Master</a></li>
    <li class="active">Jenis Imunisasi</li>
</ol>
@endsection

@section('content')
<div class="panel panel-default">
	<div class="panel-heading">Masukkan Data Jenis Imunisasi</div>
	<div class="panel-body">
		<div class="container">
			<div class="row">
				<div class="col-md-9">
					<form class="form-horizontal" method="post" action="{{ route('jenisimunisasi.store') }}">
						@csrf
						<div class="form-group">
							<div class="row">
								<label class="col-md-4 control-label" for="nama_imun">Nama Imunisasi</label>
								<div class="input-group col-md-8">
									<div class="input-group">
										<span class="input-group-addon"><i class="fa fa-eyedropper" aria-hidden="true"></i></span>
										<input type="text" class="form-control" placeholder="Nama Imunisasi" name="nama_imun" required>
									</div>
								</div>
							</div>
						</div>
						<div class="form-group">
							<div class="row">
								<label class="col-md-4 control-label" for="umur">Umur</label>
								<div class="input-group col-md-8">
									<div class="input-group">
										<span class="input-group-addon"><i class="fa fa-list-ol" aria-hidden="true"></i></span>
										<input type="number" class="form-control" placeholder="Umur" name="umur" required>
										<span class="input-group-addon"> Bulan</span>
									</div>
								</div>
							</div>
						</div>
						<div class="form-group">
							<div class="row">
								<label class="col-md-4 control-label" for="name"></label>
								<div class="input-group col-md-8">
									<button type="submit" class="btn btn-primary" style="margin-right: 6px;">Simpan</button>
									<a href="{{ route('jenisimunisasi.index') }}" class="btn btn-danger">Batal</a>
								</div>
							</div>
						</div>
					</form>
				</div>
				<div class="col-md-3"></div>
			</div>
		</div>
	</div>
</div>
@endsection

@section('java')
<!-- bootstrap datepicker -->
<script src="{!! asset('bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js') !!}"></script>
<!-- Select2 -->
<script src="{!! asset('bower_components/select2/dist/js/select2.full.min.js') !!}"></script>
<!-- iCheck 1.0.1 -->
<script src="{!! asset('plugins/iCheck/icheck.min.js') !!}"></script>
<script>
	$(function () {
		// Date Picker
		$('#datepicker').datepicker({
			format: 'yyyy/mm/dd',
			autoclose: true
		})
		//Initialize Select2 Elements
		$('.select2').select2()
		//iCheck for checkbox and radio inputs
		$('input[type="radio"].minimal').iCheck({
			checkboxClass: 'icheckbox_minimal-blue',
			radioClass   : 'iradio_minimal-blue'
		})
	})
</script>
@endsection

resources/views/admin/jenisimunisasi/edit.blade.php
@extends('layouts.base')

@section('css')
<!-- bootstrap datepicker -->
<link rel="stylesheet" href="{!! asset('bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css') !!}">
@endsection

@section('breadcrumb')
<h1>
    Jenis Imunisasi
    <small>kelola data jenis imunisasi</small>
</h1>
<ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="#">Data Master</a></li>
    <li class="active">Jenis Imunisasi</li>
</ol>
@endsection

@section('content')
<div class="panel panel-default">
	<div class="panel-heading">Edit Data Jenis Imunisasi</div>
	<div class="panel-body">
		<div class="container">
			<div class="row">
				<div class="col-md-9">
					@foreach($data as $datas)
					<form class="form-horizontal" method="post" action="{{ route('jenisimunisasi.update', $datas->id_j_imun) }}">
						@csrf
						<input name="_method" type="hidden" value="PATCH" />
						<div class="form-group">
							<div class="row">
								<label class="col-md-4 control-label" for="nama_imun">Nama Imunisasi</label>
								<div class="input-group col-md-8">
									<div class="input-group">
										<span class="input-group-addon"><i class="fa fa-eyedropper" aria-hidden="true"></i></span>
										<input type="text" class="form-control" placeholder="Nama Imunisasi" name="nama_imun" value="{{ $datas->nama_imun }}" required>
									</div>
								</div>
							</div>
						</div>
						<div class="form-group">
							<div class="row">
								<label class="col-md-4 control-label" for="umur">Umur</label>
								<div class="input-group col-md-8">
									<div class="input-group">
										<span class="input-group-addon"><i class="fa fa-list-ol" aria-hidden="true"></i></span>
										<input type="number" class="form-control" placeholder="Umur" name="umur" value="{{ $datas->umur }}" required>
										<span class="input-group-addon"> Bulan</span>
									</div>
								</div>
							</div>
						</div>
						<div class="form-group">
							<div class="row">
								<label class="col-md-4 control-label" for="name"></label>
								<div class="input-group col-md-8">
									<button type="submit" class="btn btn-primary" style="margin-right: 6px;">Update</button>
									<a href="{{ route('jenisimunisasi.index') }}" class="btn btn-danger">Batal</a>
								</div>
							</div>
						</div>
					</form>
					@endforeach
				</div>
				<div class="col-md-3"></div>
			</div>
		</div>
	</div>
</div>
@endsection

@section('java')
<!-- bootstrap datepicker -->
<script src="{!! asset('bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js') !!}"></script>
<!-- Page script -->
<script>
	$(function () {
		// Date Picker
		$('#datepicker').datepicker({
			format: 'yyyy/mm/dd',
			autoclose: true
		})
	})
</script>
@endsection

resources/views/admin/jenisimunisasi/view.blade.php
@extends('layouts.base')

@section('css')
<!-- DataTables -->
<link rel="stylesheet" href="{!! asset('bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') !!}">
@endsection

@section('breadcrumb')
<h1>
    Jenis Imunisasi
    <small>kelola data jenis imunisasi</small>
</h1>
<ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="#">Data Master</a></li>
    <li class="active">Jenis Imunisasi</li>
</ol>
@endsection

@section('content')

@include('notification')

<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title" style="margin-right: 40px"><a href="{{ route('jenisimunisasi.create') }}" class="btn btn-sm btn-primary"><span><i class="fa fa-plus-square" aria-hidden="true"></i></span> Tambah Data</a> | Jenis Imunisasi</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <div class="row" style="margin: 5px;">
                    @if(count($data) >= 1)
                        @foreach($data as $datas)
                            <div class="col-xs-6 col-sm-4 col-md-3">
                                <div class="box box-primary">
                                    <div class="box-header with-border">
                                        <h3 class="box-title">{{ $datas->nama_imun }}</h3>
                                        <div class="box-tools pull-right">
                                            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                                        </div>
                                        <!-- /.box-tools -->
                                    </div>
                                    <!-- /.box-header -->
                                    <div class="box-body">
                                        Umur : <b>{{ $datas->umur }} Bulan</b><br>
                                        Jumlah Imunisasi: <b>{{$datas->imunisasi->count()}}</b>
                                        <div class="pull-right">
                                            <form action="{{ route('jenisimunisasi.destroy', $datas->id_j_imun) }}" method="post" id="delete-form">
                                                {{ csrf_field() }}
                                                {{ method_field('DELETE') }}
                                                <div class="btn-group">
                                                    <a href="{{ route('jenisimunisasi.edit', $datas->id_j_imun) }}" class=" btn btn-sm btn-default" data-toggle="tooltip" title="Edit"><span class="glyphicon glyphicon-edit"></span></a>
                                                    {{-- <button class="btn btn-sm btn-default" type="submit" onclick="return confirm('Yakin ingin menghapus data?')" data-toggle="tooltip" title="Hapus"><span class="glyphicon glyphicon-trash"></span></button> --}}
                                                    <button class="btn btn-sm btn-danger btn-delete" data-jml-kegiatan="{{$datas->imunisasi->count()}}"><span class="glyphicon glyphicon-trash"></span></button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                    <!-- /.box-body -->
                                </div>
                            </div>
                        @endforeach
                    @else
                        <div class="col-12">
                            <div class="box box-primary">
                                <div class="box-body">
                                    <h4 style="text-align: center;">Data Kosong</h4>
                                </div>
                                <!-- /.box-body -->
                            </div>
                        </div>
                    @endif
                </div>
                <!-- <table id="example1" class="table table-bordered table-striped" style="width: 100%;">
                    <thead>
                        <tr>
                            <th style="width: 5%;text-align: center;">#</th>
                            <th style="width: 35%;text-align: center;">Nama Imunisasi</th>
                            <th style="width: 35%;text-align: center;">Umur</th>
                            <th style="width: 25%;text-align: center;">Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @php $no = 1; @endphp
                        @foreach($data as $datas)
                        <tr>
                            <td>{{ $no++ }}</td>
                            <td>{{ $datas->nama_imun }}</td>
                            <td>{{ $datas->umur }} Bulan</td>
                            <td>
                                <form action="{{ route('jenisimunisasi.destroy', $datas->id_j_imun) }}" method="post">
                                    {{ csrf_field() }}
                                    {{ method_field('DELETE') }}
                                    <div class="btn-group">
                                        <a href="{{ route('jenisimunisasi.edit', $datas->id_j_imun) }}" class=" btn btn-sm btn-warning" data-toggle="tooltip" title="Edit"><span class="glyphicon glyphicon-edit"></span></a>
                                        <button class="btn btn-sm btn-danger" type="submit" onclick="return confirm('Yakin ingin menghapus data?')" data-toggle="tooltip" title="Hapus"><span class="glyphicon glyphicon-trash"></span></button>
                                    </div>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                    <tfoot>
                        <tr>
                            <th>#</th>
                            <th>Nama Imunisasi</th>
                            <th>Umur</th>
                            <th>Aksi</th>
                        </tr>
                    </tfoot>
                </table> -->
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
</div>
@endsection

@section('java')
<!-- DataTables -->
<script src="{!! asset('bower_components/datatables.net/js/jquery.dataTables.min.js') !!}"></script>
<script src="{!! asset('bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') !!}"></script>
<script type="text/javascript">
    $(function () {
        $(document).on('click', '.btn-delete', function (e) {
            e.preventDefault();
            var jml_kegiatan = $(this).data("jml-kegiatan");
            var myhtml = document.createElement("div");
            myhtml.innerHTML = "<b>"+jml_kegiatan+" DATA IMUNISASI</b> dalam UKM ini juga akan dihapus!!";
            swal({
                title: "Data Jenis Kegiatan Akan Dihapus?",
                content: myhtml,
                icon: "warning",
                buttons: ["Batal", "Hapus!"],
                dangerMode: true,
            })
            .then((willDelete) => {
              if (willDelete) {
                $('#delete-form').submit();
              }
            });
        });
    })
</script>
@endsection