routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// route auth login dan register
Auth::routes();

Route::middleware(['guest'])->group(function(){
	Route::get('/', 'AuthController@getLogin')->name('login');
	Route::post('postlogin', 'AuthController@postLogin')->name('postlogin');
	Route::get('resetPassword', 'AuthController@resetPassword')->name('resetPassword');
	Route::post('postReset', 'AuthController@postReset')->name('postReset');
});

Route::middleware(['web', 'auth'])->group(function(){

	Route::middleware(['admin'])->group(function(){
		Route::get('admin', 'DashboardController@index')->name('admin');
		Route::resource('ibu', 'IbuController');
		Route::resource('anak', 'AnakController');
		Route::resource('ibuhamil', 'IbuHamilController');
		Route::post('bumil_meninggal', 'IbuHamilController@meninggal')->name('bumil_meninggal');
		Route::post('bumil_melahirkan', 'IbuHamilController@melahirkan')->name('bumil_melahirkan');
		Route::resource('kader', 'KaderController');
		Route::post('kaderStore1', 'KaderController@store1')->name('kaderStore1');
		Route::resource('pengguna', 'PenggunaController');
		Route::get('generatePwd/{id}', 'PenggunaController@generatePwd')->name('generatePwd');
		Route::resource('agenda', 'AgendaController');

		Route::resource('bukutamu', 'BukuTamuController');
		Route::get('checkrelasi/{id}', 'BukuTamuController@checkrelasi')->name('checkrelasi');
		Route::get('deleteBukuTamu/{id}', 'BukuTamuController@hapus');

		Route::resource('timbang', 'TimbangController');
		// timbang utk ibu


		Route::resource('imunisasi', 'ImunisasiController');
		Route::resource('vitA', 'VitAController');
		Route::resource('kegiatan', 'KegiatanController');
		Route::resource('jenisimunisasi', 'JenisImunisasiController');
		Route::resource('kehadiran', 'KehadiranController');
		Route::resource('laporan', 'LaporanController');

		Route::get('printAnak', 'AnakController@printAnak')->name('printAnak');
		Route::get('form1', 'LaporanController@form1')->name('form1');
		Route::get('form2', 'LaporanController@form2')->name('form2');
		Route::get('form3', 'LaporanController@form3')->name('form3');
		Route::get('form4', 'LaporanController@form4')->name('form4');
		Route::get('form5', 'LaporanController@form5')->name('form5');
		Route::get('form6', 'LaporanController@form6')->name('form6');
		Route::get('form7', 'LaporanController@form7')->name('form7');

		// UKM dan PKK Route
		Route::get('viewPKK', 'KegiatanController@viewPKK')->name('viewPKK');
		Route::post('storePKK', 'KegiatanController@storePKK')->name('storePKK');
		Route::get('editPKK/{id}', 'KegiatanController@editPKK')->name('editPKK');
		Route::post('updatePKK/{id}', 'KegiatanController@updatePKK')->name('updatePKK');
		Route::get('deletePKK/{id}', 'KegiatanController@deletePKK')->name('deletePKK');

		Route::get('checkindependensi/{id}', 'KegiatanController@checkindependensi')->name('checkindependensi');

		Route::get('checkindependensiukm/{id}', 'KegiatanController@checkindependensiukm')->name('checkindependensiukm');

		Route::get('viewUKM', 'KegiatanController@viewUKM')->name('viewUKM');
		Route::post('storeUKM', 'KegiatanController@storeUKM')->name('storeUKM');
		Route::get('editUKM/{id}', 'KegiatanController@editUKM')->name('editUKM');
		Route::post('updateUKM/{id}', 'KegiatanController@updateUKM')->name('updateUKM');
		Route::get('deleteUKM/{id}', 'KegiatanController@deleteUKM')->name('deleteUKM');
		/////////////

		// Status Gizi, BGM dan 2T
		Route::resource('statusgizi', 'StatusController');
		Route::get('bgm2t', 'StatusController@viewBGM')->name('viewBGM');
		/////////////

		// Gallery Route
		Route::get('albumList', 'AgendaController@albumList')->name('albumList');
		Route::post('albumStore', 'AgendaController@albumStore')->name('albumStore');
		Route::get('albumDetail/{id}', 'AgendaController@albumDetail')->name('albumDetail');
		Route::get('albumDelete/{id}', 'AgendaController@albumStore')->name('albumDelete');
		// Route::get('viewImage', 'AgendaController@viewImage')->name('viewImage');
		Route::get('addImage/{id}', 'AgendaController@addImage')->name('addImage');
		Route::post('storeImage', 'AgendaController@storeImage')->name('storeImage');
		Route::get('deleteImage/{id}', 'AgendaController@deleteImage')->name('deleteImage');

		Route::get('printAbsen/{id}', 'AgendaController@printAbsen')->name('printAbsen');
		/////////////

		// Export Excel
		Route::get('exportIbu', 'IbuController@exportIbu')->name('exportIbu');
		Route::get('exportAnak', 'AnakController@exportAnak')->name('exportAnak');
		/////////////
	});

	Route::middleware(['user'])->group(function(){
		// Route::get('user', function (){
		// 	return view('user.dashboard');
		// })->name('user');

		Route::get('user', 'IbuTimbangController@dashboard')->name('user');

		Route::get('user/anak', 'IbuTimbangController@getAnak');
		Route::get('user/timbang', 'IbuTimbangController@index')->name('timbanguser');
		Route::get('user/imunisasi', 'IbuImunisasiController@index');
		Route::get('user/vitamin', 'IbuVitaminController@index');
		Route::get('user/tumbuh/{id}', 'IbuTimbangController@detailanak')->name('tumbuhanak');

	});

	Route::get('getProfile', 'DashboardController@getProfile')->name('getProfile');
	Route::post('postProfile', 'DashboardController@postProfile')->name('postProfile');
	Route::get('logout', 'DashboardController@getLogout')->name('logout');
});



// Route::middleware(['web', 'auth'])->group(function (){

// 	Route::get('/', 'DashboardController@index');

// 	Route::middleware(['admin'])->group(function(){
// 		Route::get('admin', function (){
// 			return view('admin.dashboard');
// 		});
// 		Route::resource('ibu', 'IbuController');
// 		Route::resource('anak', 'AnakController');
// 		Route::resource('ibuhamil', 'IbuHamilController');
// 		Route::resource('kader', 'KaderController');
// 		Route::resource('pengguna', 'PenggunaController');
// 		Route::resource('agenda', 'AgendaController');
// 		Route::resource('bukutamu', 'BukuTamuController');
// 		Route::resource('timbang', 'TimbangController');
// 		Route::resource('vitA', 'VitAController');
// 		Route::resource('kegiatan', 'KegiatanController');
// 		Route::resource('jenisimunisasi', 'JenisImunisasiController');
// 	});

// 	Route::middleware(['user'])->group(function(){
// 		Route::get('user', function (){
// 			return view('user.dashboard');
// 		});
// 	});
// });


Route::get('/home', 'HomeController@index')->name('home');

app/Timbang.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Timbang extends Model
{
    protected $table = 'timbangs';
    protected $primaryKey = 'id_timbang';
}

app/Http/Controllers/TimbangController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Anak;
use App\Timbang;
use App\VitA;
use App\JenisImunisasi;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class TimbangController extends Controller
{
    public function __construct()
    {
        $this->middleware('admin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        date_default_timezone_set('Asia/Jakarta');
        $nm = Carbon::now()->format('m'); // Tanggal sekarang bulan
        $nY = Carbon::now()->format('Y'); // Tanggal sekarang tahun
        $data = DB::table('timbangs as T')
                ->leftjoin('anaks as A', 'T.id_anak', '=', 'A.id_anak')
                ->whereMonth('T.tgl_timbang', $nm)
                ->whereYear('T.tgl_timbang', $nY)
                ->get();
        $data2 = DB::table('timbangs as T')
                ->leftjoin('anaks as A', 'T.id_anak', '=', 'A.id_anak')
                ->get();
        return view('admin.timbang.view', compact('data','data2'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $dataKelamin = null;
        $grafik = array(60);
        for ($i=0; $i < 60; $i++) { 
            $grafik[$i] = null;
        }
        $dataCreate = DB::table('anaks as A')
                ->leftjoin('users as I', 'I.id', '=', 'A.id_ibu')
                ->orderBy('nama_anak', 'asc')
                ->get();
        return view('admin.timbang.create', compact('dataCreate','dataKelamin'))->with('grafik',json_encode($grafik,JSON_NUMERIC_CHECK));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $idA = $request->get('id_anak');
        date_default_timezone_set('Asia/Jakarta');
        $nm = Carbon::now()->format('m'); // Tanggal sekarang bulan
        $nY = Carbon::now()->format('Y'); // Tanggal sekarang tahun
        $check = DB::table('timbangs')
                ->whereMonth('tgl_timbang', $nm)->whereYear('tgl_timbang', $nY)
                ->where('id_anak', $idA)
                ->first();
        if ($check == null) {
            // menerima data request
            $data               = new Timbang;
            $data->id_anak      = $request->get('id_anak');
            $data->berat_badan  = $request->get('berat_badan');
            $data->tinggi_badan = $request->get('tinggi_badan');

            //////////Umur
            $id = $request->get('id_anak');
            $anak = Anak::where('id_anak', $id)->first();
            date_default_timezone_set('Asia/Jakarta');
            $now = Carbon::now()->format('Y-m-d'); // Tanggal sekarang
            $b_day = Carbon::parse($anak->tgl_lhr); // Tanggal Lahir
            $age = $b_day->diffInMonths($now);  // Menghitung umur

            $data->umur = $age;
            $data->tgl_timbang = $now;
            /////////Umur End

            ////////Status Gizi Cek BB/U
            $umur = $age;
            $bb = $data->berat_badan;
            $jk = $anak->jenis_kelamin;
            if ($jk == 1) {
                if ($umur <= 1) {
                    if ($bb < 2.8) {
                        $q = "BB Sangat Kurang";
                    } elseif ($bb >= 2.8 && $bb < 3.1) {
                        $q = "BB Kurang";
                    } elseif ($bb >= 3.1 && $bb < 5.5) {
                        $q = "BB Normal";
                    } else {
                        $q = "BB Lebih";
                    }
                } elseif ($umur == 2) {
                    if ($bb < 3.4) {
                        $q = "BB Sangat Kurang";
                    } elseif ($bb >= 3.4 && $bb < 3.9) {
                        $q = "BB Kurang";
                    } elseif ($bb >= 3.9 && $bb < 6.6) {
                        $q = "BB Normal";
                    } else {
                        $q = "BB Lebih";
                    }
                } elseif ($umur == 3) {
                    if ($bb < 4.0) {
                        $q = "BB Sangat Kurang";
                    } elseif ($bb >= 4.0 && $bb < 4.5) {
                        $q = "BB Kurang";
                    } elseif ($bb >= 4.5 && $bb < 7.5) {
                        $q = "BB Normal";
                    } else {
                        $q = "BB Lebih";
                    }
                } elseif ($umur == 4) {
                    if ($bb < 4.4) {
                        $q = "BB Sangat Kurang";
                    } elseif ($bb >= 4.4 && $bb < 5.0) {
                        $q = "BB Kurang";
                    } elseif ($bb >= 5.0 && $bb < 8.2) {
                        $q = "BB Normal";
                    } else {
                        $q = "BB Lebih";
                    }
                } elseif ($umur == 5) {
                    if ($bb < 4.8) {
                        $q = "BB Sangat Kurang";
                    } elseif ($bb >= 4.8 && $bb < 5.4) {
                        $q = "BB Kurang";
                    } elseif ($bb >= 5.4 && $bb < 8.8) {
                        $q = "BB Normal";
                    } else {
                        $q = "BB Lebih";
                    }
                } elseif ($umur == 6) {
                    if ($bb < 5.1) {
                        $q = "BB Sangat Kurang";
                    } elseif ($bb >= 5.1 && $bb < 5.7) {
                        $q = "BB Kurang";
                    } elseif ($bb >= 5.7 && $bb < 9.3) {
                        $q = "BB Normal";
                    } else {
                        $q = "BB Lebih";
                    }
                } elseif ($umur == 7) {
                    if ($bb < 5.3) {
                        $q = "BB Sangat Kurang";
                    } elseif ($bb >= 5.3 && $bb < 6) {
                        $q = "BB Kurang";
                    } elseif ($bb >= 6 && $bb < 9.8) {
                        $q = "BB Normal";
                    } else {
                        $q = "BB Lebih";
                    }
                } elseif ($umur == 8) {
                    if ($bb < 5.6) {
                        $q = "BB Sangat Kurang";
                    } elseif ($bb >= 5.6 && $bb < 6.2) {
                        $q = "BB Kurang";
                    } elseif ($bb >= 6.2 && $bb < 10.2) {
                        $q = "BB Normal";
                    } else {
                        $q = "BB Lebih";
                    }
                } elseif ($umur == 9) {
                    if ($bb < 5.8) {
                        $q = "BB Sangat Kurang";
                    } elseif ($bb >= 5.8 && $bb < 6.5) {
                        $q = "BB Kurang";
                    } elseif ($bb >= 6.5 && $bb < 10.5) {
                        $q = "BB Normal";
                    } else {
                        $q = "BB Lebih";
                    }
                } elseif ($umur == 10) {
                    if ($bb < 6) {
                        $q = "BB Sangat Kurang";
                    } elseif ($bb >= 6 && $bb < 6.7) {
                        $q = "BB Kurang";
                    } elseif ($bb >= 6.7 && $bb < 10.9) {
                        $q = "BB Normal";
                    } else {
                        $q = "BB Lebih";
                    }
                } elseif ($umur == 11) {
                    if ($bb < 6.1) {
                        $q = "BB Sangat Kurang";
                    } elseif ($bb >= 6.1 && $bb < 6.9) {
                        $q = "BB Kurang";
                    } elseif ($bb >= 6.9 && $bb < 11.2) {
                        $q = "BB Normal";
                    } else {
                        $q = "BB Lebih";
                    }
                } elseif ($umur == 12) {
                    if ($bb < 6.3) {
                        $q = "BB Sangat Kurang";
                    } elseif ($bb >= 6.3 && $bb < 7) {
                        $q = "BB Kurang";
                    } elseif ($bb >= 7 && $bb < 11.5) {
                        $q = "BB Normal";
                    } else {
                        $q = "BB Lebih";
                    }
                } elseif ($umur == 13) {
                    if ($bb < 6.4) {
                        $q = "BB Sangat Kurang";
                    } elseif ($bb >= 6.4 && $bb < 7.2) {
                        $q = "BB Kurang";
                    } elseif ($bb >= 7.2 && $bb < 11.8) {
                        $q = "BB Normal";
                    } else {
                        $q = "BB Lebih";
                    }
                } elseif ($umur == 14) {
                    if ($bb < 6.6) {
                        $q = "BB Sangat Kurang";
                    } elseif ($bb >= 6.6 && $bb < 7.4) {
                        $q = "BB Kurang";
                    } elseif ($bb >= 7.4 && $bb < 12.1) {
                        $q = "BB Normal";
                    } else {
                        $q = "BB Lebih";
                    }
                } elseif ($umur == 15) {
                    if ($bb < 6.8) {
                        $q = "BB Sangat Kurang";
                    } elseif ($bb >= 6.8 && $bb < 7.6) {
                        $q = "BB Kurang";
                    } elseif ($bb >= 7.6 && $bb < 12.4) {
                        $q = "BB Normal";
                    } else {
                        $q = "BB Lebih";
                    }
                } elseif ($umur == 16) {
                    if ($bb < 6.9) {
                        $q = "BB Sangat Kurang";
                    } elseif ($bb >= 6.9 && $bb < 7.7) {
                        $q = "BB Kurang";
                    } elseif ($bb >= 7.7 && $bb < 12.6) {
                        $q = "BB Normal";
                    } else {
                        $q = "BB Lebih";
                    }

resources/views/admin/timbang/edit.blade.php
@extends('layouts.base')

@section('css')
<!-- bootstrap datepicker -->
<link rel="stylesheet" href="{!! asset('bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css') !!}">
<!-- Select2 -->
<link rel="stylesheet" href="{!! asset('bower_components/select2/dist/css/select2.min.css') !!}">
<!-- Theme style -->
<link rel="stylesheet" href="{!! asset('dist/css/AdminLTE.min.css') !!}">
@endsection

@section('breadcrumb')
<h1>
    Timbang Anak
    <small>penimbangan anak</small>
</h1>
<ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">Timbang Anak</li>
</ol>
@endsection

@section('content')
<div class="panel panel-default">
	<div class="panel-heading">Edit Data Timbang</div>
	<div class="panel-body">
		<div class="container">
			<div class="row">
				<div class="col-md-9">
					@foreach($data as $datas)
					<form class="form-horizontal" method="post" action="{{ route('timbang.update', $datas->id_timbang) }}">
						@csrf
						<input name="_method" type="hidden" value="PATCH" />
						<div class="form-group">
							<div class="row">
								<label class="col-md-4 control-label" for="id_anak">Nama Anak</label>
								<div class="input-group col-md-8">
									<div class="input-group">
										<span class="input-group-addon"><i class="fa fa-child"></i></span>
										<select class="form-control select2" name="id_anak" style="width: 100%;" required>
											<option selected="selected" value="{{ $datas->id_anak }}">{{ $datas->nama_anak }}</option>
											<option value="">-- Nama Anak --</option>
											@foreach($data2 as $datas2)
												<option value="{{ $datas2->id_anak }}">{{ $datas2->nama_anak }} - {{ $datas2->nama_ibu }} & {{ $datas2->nama_suami }}</option>
											@endforeach
										</select>
									</div>
								</div>
							</div>
						</div>
						<div class="form-group form-inline">
							<div class="row">
								<label class="col-md-4 control-label" for="alamat2">Berat dan Tinggi Badan</label>
								<div class="input-group col-md-8">
									<div class="input-group" style="padding-right: 6px;">
										<span class="input-group-addon"><i class="fa fa-balance-scale"></i></span>
										<input type="text" class="form-control" placeholder="Berat Badan" name="berat_badan" value="{{ $datas->berat_badan }}" required>
										<span class="input-group-addon">Kg</span>
									</div>
									<div class="input-group">
										<span class="input-group-addon"><i class="fa fa-long-arrow-up"></i></span>
										<input type="text" class="form-control" placeholder="Tinggi Badan" name="tinggi_badan" value="{{ $datas->tinggi_badan }}" required>
										<span class="input-group-addon">cm</span>
									</div>
								</div>
							</div>
						</div>
						<div class="form-group form-inline">
							<div class="row">
								<label class="col-md-4 control-label" for="tgl_timbang">Tanggal Timbang</label>
								<div class="input-group col-md-8">
									<div class="input-group date">
										<div class="input-group-addon">
											<i class="fa fa-calendar"></i>
										</div>
										<input type="text" class="form-control pull-right" id="datepicker" placeholder="Tanggal Imunisasi" name="tgl_timbang" value="{{ $datas->tgl_timbang }}" required autocomplete="off">
									</div>
								</div>
							</div>
						</div>
						<div class="form-group">
							<div class="row">
								<label class="col-md-4 control-label" for="name"></label>
								<div class="input-group col-md-8">
									<button type="submit" class="btn btn-primary" style="margin-right: 6px;">Simpan</button>
									<a href="{{ route('timbang.index') }}" class="btn btn-danger">Batal</a>
								</div>
							</div>
						</div>
					</form>
					@endforeach
				</div>
				<div class="col-md-3"></div>
			</div>
		</div>
	</div>
</div>
@endsection

@section('java')
<!-- bootstrap datepicker -->
<script src="{!! asset('bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js') !!}"></script>
<!-- Select2 -->
<script src="{!! asset('bower_components/select2/dist/js/select2.full.min.js') !!}"></script>
<!-- iCheck 1.0.1 -->
<script src="{!! asset('plugins/iCheck/icheck.min.js') !!}"></script>
<!-- Page script -->
<script>
	$(function () {
		// Date Picker
		$('#datepicker').datepicker({
			format: 'yyyy/mm/dd',
			autoclose: true
		})
		//Initialize Select2 Elements
		$('.select2').select2()
	})
</script>
@endsection

resources/views/admin/timbang/view.blade.php
@extends('layouts.base')

@section('css')
<!-- DataTables -->
<link rel="stylesheet" href="{!! asset('bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') !!}">
@endsection

@section('breadcrumb')
<h1>
    Timbang Anak
    <small>penimbangan anak</small>
</h1>
<ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">Timbang Anak</li>
</ol>
@endsection

@section('content')

@include('notification')

<div class="nav-tabs-custom">
    <ul class="nav nav-tabs pull-right">
        <li><a href="#tab_2-2" data-toggle="tab">Data Timbang</a></li>
        <li class="active"><a href="#tab_1-1" data-toggle="tab">Data Timbang Bulan Ini</a></li>
        <li class="pull-left header"><h4>Hasil Timbang Anak</h4></li>
    </ul>
    <!-- Bulan INI -->
    <div class="tab-content">
        <div class="tab-pane active" id="tab_1-1">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                        <div class="box-body">
                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Nama Anak</th>
                                        <th>Umur</th>
                                        <th>BB/TB</th>
                                        <th>Tanggal Timbang</th>
                                        <th>Status Gizi</th>
                                        <th>Keterangan</th>
                                        <th>Aksi</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @php $no = 1; @endphp
                                    @foreach($data as $datas)
                                    <tr>
                                        <td>{{ $no++ }}</td>
                                        <td>{{ $datas->nama_anak }}</td>
                                        <td>{{ $datas->umur }} Bulan</td>
                                        <td>
                                            {{ $datas->berat_badan }} Kg/{{ $datas->tinggi_badan }} cm
                                        </td>
                                        <td>{{ $datas->tgl_timbang }}</td>
                                        <td>{{ $datas->status_gizi }}</td>
                                        <td>{{ $datas->ket_timbang }}</td>
                                        <td>
                                            <!-- <form action="{{ route('timbang.destroy', $datas->id_timbang) }}" method="post">
                                                {{ csrf_field() }}
                                                {{ method_field('DELETE') }} -->
                                                <div class="btn-group">
                                                    <a href="{{ route('timbang.edit', $datas->id_timbang) }}" class=" btn btn-sm btn-warning" data-toggle="tooltip" title="Edit"><span class="glyphicon glyphicon-edit"></span></a>
                                                    <!-- <button class="btn btn-sm btn-danger" type="submit" onclick="return confirm('Yakin ingin menghapus data?')" data-toggle="tooltip" title="Hapus"><span class="glyphicon glyphicon-trash"></span></button> -->
                                                </div>
                                            <!-- </form> -->
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th>#</th>
                                        <th>Nama Anak</th>
                                        <th>Umur</th>
                                        <th>BB/TB</th>
                                        <th>Tanggal Timbang</th>
                                        <th>Status Gizi</th>
                                        <th>Keterangan</th>
                                        <th>Aksi</th>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                </div>
            </div>
        </div>
        <!-- /.tab-pane -->
        <div class="tab-pane" id="tab_2-2">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                        <div class="box-body">
                            <table id="example2" class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Nama Anak</th>
                                        <th>Umur</th>
                                        <th>BB/TB</th>
                                        <th>Tanggal Timbang</th>
                                        <th>Status Gizi</th>
                                        <th>Keterangan</th>
                                        <th>Aksi</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @php $no = 1; @endphp
                                    @foreach($data2 as $datas2)
                                    <tr>
                                        <td>{{ $no++ }}</td>
                                        <td>{{ $datas2->nama_anak }}</td>
                                        <td>{{ $datas2->umur }} Bulan</td>
                                        <td>
                                            {{ $datas2->berat_badan }} Kg/{{ $datas2->tinggi_badan }} cm
                                        </td>
                                        <td>{{ $datas2->tgl_timbang }}</td>
                                        <td>{{ $datas2->status_gizi }}</td>
                                        <td>{{ $datas2->ket_timbang }}</td>
                                        <td>
                                            <!-- <form action="{{ route('timbang.destroy', $datas2->id_timbang) }}" method="post">
                                                {{ csrf_field() }}
                                                {{ method_field('DELETE') }} -->
                                                <div class="btn-group">
                                                    <a href="{{ route('timbang.edit', $datas2->id_timbang) }}" class=" btn btn-sm btn-warning" data-toggle="tooltip" title="Edit"><span class="glyphicon glyphicon-edit"></span></a>
                                                    <!-- <button class="btn btn-sm btn-danger" type="submit" onclick="return confirm('Yakin ingin menghapus data?')" data-toggle="tooltip" title="Hapus"><span class="glyphicon glyphicon-trash"></span></button> -->
                                                </div>
                                            <!-- </form> -->
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th>#</th>
                                        <th>Nama Anak</th>
                                        <th>Umur</th>
                                        <th>BB/TB</th>
                                        <th>Tanggal Timbang</th>
                                        <th>Status Gizi</th>
                                        <th>Keterangan</th>
                                        <th>Aksi</th>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                </div>
            </div>
        </div>
        <!-- /.tab-pane -->
    </div>
    <!-- /.tab-content -->
</div>
<!-- nav-tabs-custom -->
@endsection

@section('java')
<!-- DataTables -->
<script src="{!! asset('bower_components/datatables.net/js/jquery.dataTables.min.js') !!}"></script>
<script src="{!! asset('bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') !!}"></script>
<script type="text/javascript">
    $(function () {
        $('#example1').DataTable();
        $('#example2').DataTable();
    })
</script>
@endsection