routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// route auth login dan register
Auth::routes();

Route::middleware(['guest'])->group(function(){
	Route::get('/', 'AuthController@getLogin')->name('login');
	Route::post('postlogin', 'AuthController@postLogin')->name('postlogin');
	Route::get('resetPassword', 'AuthController@resetPassword')->name('resetPassword');
	Route::post('postReset', 'AuthController@postReset')->name('postReset');
});

Route::middleware(['web', 'auth'])->group(function(){

	Route::middleware(['admin'])->group(function(){
		Route::get('admin', 'DashboardController@index')->name('admin');
		Route::resource('ibu', 'IbuController');
		Route::resource('anak', 'AnakController');
		Route::resource('ibuhamil', 'IbuHamilController');
		Route::post('bumil_meninggal', 'IbuHamilController@meninggal')->name('bumil_meninggal');
		Route::post('bumil_melahirkan', 'IbuHamilController@melahirkan')->name('bumil_melahirkan');
		Route::resource('kader', 'KaderController');
		Route::post('kaderStore1', 'KaderController@store1')->name('kaderStore1');
		Route::resource('pengguna', 'PenggunaController');
		Route::get('generatePwd/{id}', 'PenggunaController@generatePwd')->name('generatePwd');
		Route::resource('agenda', 'AgendaController');

		Route::resource('bukutamu', 'BukuTamuController');
		Route::get('checkrelasi/{id}', 'BukuTamuController@checkrelasi')->name('checkrelasi');
		Route::get('deleteBukuTamu/{id}', 'BukuTamuController@hapus');

		Route::resource('timbang', 'TimbangController');
		// timbang utk ibu


		Route::resource('imunisasi', 'ImunisasiController');
		Route::resource('vitA', 'VitAController');
		Route::resource('kegiatan', 'KegiatanController');
		Route::resource('jenisimunisasi', 'JenisImunisasiController');
		Route::resource('kehadiran', 'KehadiranController');
		Route::resource('laporan', 'LaporanController');

		Route::get('printAnak', 'AnakController@printAnak')->name('printAnak');
		Route::get('form1', 'LaporanController@form1')->name('form1');
		Route::get('form2', 'LaporanController@form2')->name('form2');
		Route::get('form3', 'LaporanController@form3')->name('form3');
		Route::get('form4', 'LaporanController@form4')->name('form4');
		Route::get('form5', 'LaporanController@form5')->name('form5');
		Route::get('form6', 'LaporanController@form6')->name('form6');
		Route::get('form7', 'LaporanController@form7')->name('form7');

		// UKM dan PKK Route
		Route::get('viewPKK', 'KegiatanController@viewPKK')->name('viewPKK');
		Route::post('storePKK', 'KegiatanController@storePKK')->name('storePKK');
		Route::get('editPKK/{id}', 'KegiatanController@editPKK')->name('editPKK');
		Route::post('updatePKK/{id}', 'KegiatanController@updatePKK')->name('updatePKK');
		Route::get('deletePKK/{id}', 'KegiatanController@deletePKK')->name('deletePKK');

		Route::get('checkindependensi/{id}', 'KegiatanController@checkindependensi')->name('checkindependensi');

		Route::get('checkindependensiukm/{id}', 'KegiatanController@checkindependensiukm')->name('checkindependensiukm');

		Route::get('viewUKM', 'KegiatanController@viewUKM')->name('viewUKM');
		Route::post('storeUKM', 'KegiatanController@storeUKM')->name('storeUKM');
		Route::get('editUKM/{id}', 'KegiatanController@editUKM')->name('editUKM');
		Route::post('updateUKM/{id}', 'KegiatanController@updateUKM')->name('updateUKM');
		Route::get('deleteUKM/{id}', 'KegiatanController@deleteUKM')->name('deleteUKM');
		/////////////

		// Status Gizi, BGM dan 2T
		Route::resource('statusgizi', 'StatusController');
		Route::get('bgm2t', 'StatusController@viewBGM')->name('viewBGM');
		/////////////

		// Gallery Route
		Route::get('albumList', 'AgendaController@albumList')->name('albumList');
		Route::post('albumStore', 'AgendaController@albumStore')->name('albumStore');
		Route::get('albumDetail/{id}', 'AgendaController@albumDetail')->name('albumDetail');
		Route::get('albumDelete/{id}', 'AgendaController@albumStore')->name('albumDelete');
		// Route::get('viewImage', 'AgendaController@viewImage')->name('viewImage');
		Route::get('addImage/{id}', 'AgendaController@addImage')->name('addImage');
		Route::post('storeImage', 'AgendaController@storeImage')->name('storeImage');
		Route::get('deleteImage/{id}', 'AgendaController@deleteImage')->name('deleteImage');

		Route::get('printAbsen/{id}', 'AgendaController@printAbsen')->name('printAbsen');
		/////////////

		// Export Excel
		Route::get('exportIbu', 'IbuController@exportIbu')->name('exportIbu');
		Route::get('exportAnak', 'AnakController@exportAnak')->name('exportAnak');
		/////////////
	});

	Route::middleware(['user'])->group(function(){
		// Route::get('user', function (){
		// 	return view('user.dashboard');
		// })->name('user');

		Route::get('user', 'IbuTimbangController@dashboard')->name('user');

		Route::get('user/anak', 'IbuTimbangController@getAnak');
		Route::get('user/timbang', 'IbuTimbangController@index')->name('timbanguser');
		Route::get('user/imunisasi', 'IbuImunisasiController@index');
		Route::get('user/vitamin', 'IbuVitaminController@index');
		Route::get('user/tumbuh/{id}', 'IbuTimbangController@detailanak')->name('tumbuhanak');

	});

	Route::get('getProfile', 'DashboardController@getProfile')->name('getProfile');
	Route::post('postProfile', 'DashboardController@postProfile')->name('postProfile');
	Route::get('logout', 'DashboardController@getLogout')->name('logout');
});



// Route::middleware(['web', 'auth'])->group(function (){

// 	Route::get('/', 'DashboardController@index');

// 	Route::middleware(['admin'])->group(function(){
// 		Route::get('admin', function (){
// 			return view('admin.dashboard');
// 		});
// 		Route::resource('ibu', 'IbuController');
// 		Route::resource('anak', 'AnakController');
// 		Route::resource('ibuhamil', 'IbuHamilController');
// 		Route::resource('kader', 'KaderController');
// 		Route::resource('pengguna', 'PenggunaController');
// 		Route::resource('agenda', 'AgendaController');
// 		Route::resource('bukutamu', 'BukuTamuController');
// 		Route::resource('timbang', 'TimbangController');
// 		Route::resource('vitA', 'VitAController');
// 		Route::resource('kegiatan', 'KegiatanController');
// 		Route::resource('jenisimunisasi', 'JenisImunisasiController');
// 	});

// 	Route::middleware(['user'])->group(function(){
// 		Route::get('user', function (){
// 			return view('user.dashboard');
// 		});
// 	});
// });


Route::get('/home', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'nama_ibu', 'nama_suami', 'tempat_lahir', 'tgl_lahir', 'alamat', 'rt', 'rw', 'kelurahan', 'kecamatan', 'No_tlp', 'agama', 'NIK', 'No_KK', 'No_BPJS', 'gakin', 'jabatan', 'email', 'password', 'level',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'remember_token',
    ];

    protected $table = 'users';
}

resources/views/admin/user/create.blade.php
@extends('layouts.base')

@section('css')
<!-- Select2 -->
<link rel="stylesheet" href="{!! asset('bower_components/select2/dist/css/select2.min.css') !!}">
<!-- Theme style -->
<link rel="stylesheet" href="{!! asset('dist/css/AdminLTE.min.css') !!}">
@endsection

@section('breadcrumb')
<h1>
    Data Pengguna Aplikasi
    <small>kelola data pengguna</small>
</h1>
<ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">Data Pengguna Aplikasi</li>
</ol>
@endsection

@section('content')
<div class="panel panel-default">
	<div class="panel-heading">Tambah Data User</div>
	<div class="panel-body">
		<div class="container">
			<div class="row">
				<div class="col-md-9">
					<form class="form-horizontal" method="POST" action="{{ route('pengguna.store') }}">
						@csrf
						<!-- <input name="_method" type="hidden" value="PATCH" /> -->
						<div class="form-group">
							<div class="row">
								<label class="col-md-4 control-label" for="id">Nama Ibu</label>
								<div class="input-group col-md-8">
									<div class="input-group">
										<span class="input-group-addon"><i class="fa fa-venus-mars"></i></span>
										<select class="form-control select2" name="id" style="width: 100%;" required>
											<option selected="selected" value="">-- Nama Ibu --</option>
											@foreach($data as $datas)
												<option value="{{ $datas->id }}">{{ $datas->nama_ibu }} - {{ $datas->nama_suami }}</option>
											@endforeach
										</select>
									</div>
								</div>
							</div>
						</div>
						<div class="form-group">
							<div class="row">
								<label class="col-md-4 control-label" for="email">Email</label>
								<div class="input-group col-md-8">
									<div class="input-group">
										<span class="input-group-addon"><i class="fa fa-envelope-o"></i></span>
										<input type="text" class="form-control" placeholder="Email" name="email" required>
									</div>
								</div>
							</div>
						</div>

						<div class="form-group">
							<div class="row">
								<label class="col-md-4 control-label" for="password"> Password </label>
								<div class="input-group col-md-8">
									<div class="input-group">
										<span class="input-group-addon"><i class="fa fa-key"></i></span>
										<input type="password" class="form-control" placeholder="Password" name="password" required>
									</div>
								</div>
							</div>
						</div>

						<div class="form-group">
							<div class="row">
								<label class="col-md-4 control-label" for="level">Level</label>
								<div class="input-group col-md-8">
									<div class="input-group">
										<span class="input-group-addon"><i class="fa fa-venus-mars"></i></span>
										<select class="form-control" name="level" style="width: 100%;">
											<option selected="selected" value="">-- Level --</option>
											<option value="0">User Ibu</option>
											<option value="1">Admin</option>
										</select>
									</div>
								</div>
							</div>
						</div>
						<div class="form-group">
							<div class="row">
								<label class="col-md-4 control-label" for="name"></label>
								<div class="input-group col-md-8">
									<button type="submit" class="btn btn-primary" style="margin-right: 6px;">Simpan</button>
									<a href="{{ route('pengguna.index') }}" class="btn btn-danger">Batal</a>
								</div>
							</div>
						</div>
					</form>
				</div>
				<div class="col-md-3"></div>
			</div>
		</div>
	</div>
</div>
@endsection

@section('java')
<!-- Select2 -->
<script src="{!! asset('bower_components/select2/dist/js/select2.full.min.js') !!}"></script>
<script>
	$(function () {
		//Initialize Select2 Elements
		$('.select2').select2()
	})
</script>
@endsection

resources/views/admin/user/edit.blade.php
@extends('layouts.base')

@section('css')
<!-- bootstrap datepicker -->
<link rel="stylesheet" href="{!! asset('bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css') !!}">
@endsection

@section('breadcrumb')
<h1>
    Data Pengguna Aplikasi
    <small>kelola data pengguna</small>
</h1>
<ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">Data Pengguna Aplikasi</li>
</ol>
@endsection

@section('content')
<div class="panel panel-default">
	<div class="panel-heading">Edit Data Pengguna</div>
	<div class="panel-body">
		<div class="container">
			<div class="row">
				<div class="col-md-9">
					@foreach($data as $datas)
					<form class="form-horizontal" method="post" action="{{ route('pengguna.update', $datas->id) }}">
						@csrf
						<input name="_method" type="hidden" value="PATCH" />
						<div class="form-group">
							<div class="row">
								<label class="col-md-4 control-label" for="nama_anak">Nama Ibu</label>
								<div class="input-group col-md-8">
									<div class="input-group">
										<span class="input-group-addon"><i class="fa fa-venus-mars"></i></span>
										<input type="text" class="form-control" placeholder="Nama Pengguna" name="id_ibu" value="{{ $datas->nama_ibu }}" required>
									</div>
								</div>
							</div>
						</div>
						<div class="form-group">
							<div class="row">
								<label class="col-md-4 control-label" for="alamat">Email</label>
								<div class="input-group col-md-8">
									<div class="input-group">
										<span class="input-group-addon"><i class="fa fa-home"></i></span>
										<input type="text" class="form-control" placeholder="Email" name="email" value="{{ $datas->email }}" required>
									</div>
								</div>
							</div>
						</div>
						<div class="form-group">
							<div class="row">
								<label class="col-md-4 control-label" for="alamat"> Password </label>
								<div class="input-group col-md-8">
									<div class="input-group">
										<span class="input-group-addon"><i class="fa fa-key"></i></span>
										<input type="text" class="form-control" placeholder="Masukkan Password Baru" name="password" value="" required>
									</div>
								</div>
							</div>
						</div>
						<div class="form-group">
							<div class="row">
								<label class="col-md-4 control-label" for="nama_anak">Level</label>
								<div class="input-group col-md-8">
									<div class="input-group">
										<span class="input-group-addon"><i class="fa fa-venus-mars"></i></span>
										<select class="form-control" name="level" style="width: 100%;">
											<option selected="selected" value="{{ $datas->level }}">
												@if ($datas->level == 1)
				                                    {{ 'Admin' }}
				                                @else
				                                    {{ 'User' }}
				                                @endif
											</option>
											<option disabled="disabled">-- Level --</option>
											@if ($datas->level == 1)
												<option value="0">User</option>
											@else
												<option value="1">Admin</option>
											@endif
										</select>
									</div>
								</div>
							</div>
						</div>
						<div class="form-group">
							<div class="row">
								<label class="col-md-4 control-label" for="name"></label>
								<div class="input-group col-md-8">
									<button type="submit" class="btn btn-primary" style="margin-right: 6px;">Update</button>
									<a href="{{ route('pengguna.index') }}" class="btn btn-danger">Batal</a>
								</div>
							</div>
						</div>
					</form>
					@endforeach
				</div>
				<div class="col-md-3"></div>
			</div>
		</div>
	</div>
</div>
@endsection

@section('java')
<!-- bootstrap datepicker -->
<script src="{!! asset('bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js') !!}"></script>
<!-- Page script -->
<script>
	$(function () {
		// Date Picker
		$('#datepicker').datepicker({
			format: 'yyyy/mm/dd',
			autoclose: true
		})
	})
</script>
@endsection

resources/views/admin/user/view.blade.php
@extends('layouts.base')

@section('css')
<!-- DataTables -->
<link rel="stylesheet" href="{!! asset('bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') !!}">
@endsection

@section('breadcrumb')
<h1>
    Data Pengguna Aplikasi
    <small>kelola data pengguna</small>
</h1>
<ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">Data Pengguna Aplikasi</li>
</ol>
@endsection

@section('content')

@include('notification')

<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title" style="margin-right: 40px"><a href="{{ route('pengguna.create') }}" class="btn btn-sm btn-primary"><span><i class="fa fa-plus-square" aria-hidden="true"></i></span> Tambah Data</a> | Data Pengguna Aplikasi</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <!-- <th style="width: 5%;text-align: center;">#</th>
                            <th style="width: 27%;text-align: center;">Nama</th>
                            <th style="width: 27%;text-align: center;">Email</th>
                            <th style="width: 26%;text-align: center;">Level</th>
                            <th style="width: 15%;text-align: center;">Aksi</th> -->
                            <th style="text-align: center;">#</th>
                            <th style="text-align: center;">Nama</th>
                            <th style="text-align: center;">Email</th>
                            <th style="text-align: center;">Level</th>
                            <th style="text-align: center;">PWD</th>
                            <th style="text-align: center;">Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @php $no = 1; @endphp
                        @foreach($data as $datas)
                        <tr>
                            <td>{{ $no++ }}</td>
                            <td>{{ $datas->nama_ibu }}</td>
                            <td>{{ $datas->email }}</td>
                            <td>
                                @if ($datas->level == 1)
                                    <span class="label label-primary">
                                        {{ 'Admin' }}
                                    </span>
                                @else
                                    <span class="label label-success">
                                        {{ 'User Ibu' }}
                                    </span>
                                @endif
                                </span>
                            </td>
                            <td>{{ ($datas->password) }}</td>
                            <td>
                                <form action="{{ route('pengguna.destroy', $datas->id) }}" method="post">
                                    {{ csrf_field() }}
                                    {{ method_field('DELETE') }}
                                    <div class="btn-group">
                                        <a href="{{ route('pengguna.edit', $datas->id) }}" class=" btn btn-sm btn-warning" data-toggle="tooltip" title="Edit"><span class="glyphicon glyphicon-edit"></span></a>
                                        <a href="{{ route('generatePwd', $datas->id) }}" class=" btn btn-sm btn-info" data-toggle="tooltip" title="Paswword Baru"><span class="glyphicon glyphicon-wrench"></span></a>
                                        <button class="btn btn-sm btn-danger" type="submit" onclick="return confirm('Yakin ingin menghapus data?')" data-toggle="tooltip" title="Hapus"><span class="glyphicon glyphicon-trash"></span></button>
                                    </div>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                    <tfoot>
                        <tr>
                            <th style="text-align: center;">#</th>
                            <th style="text-align: center;">Nama</th>
                            <th style="text-align: center;">Email</th>
                            <th style="text-align: center;">Level</th>
                            <th style="text-align: center;">PWD</th>
                            <th style="text-align: center;">Aksi</th>
                        </tr>
                    </tfoot>
                </table>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
</div>
@endsection

@section('java')
<!-- DataTables -->
<script src="{!! asset('bower_components/datatables.net/js/jquery.dataTables.min.js') !!}"></script>
<script src="{!! asset('bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') !!}"></script>
<script type="text/javascript">
    $(function () {
        $('#example1').DataTable()
    })
</script>
@endsection